---
name: PR tests

on:
  pull_request_target:
    branches:
      - current
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Build:
    name: "Build against Slackware 15"
    runs-on: ubuntu-22.04

    container:
      image: aclemons/slackware:latest-full

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Slackware 15.0 vs my -current
      run: |
        ( export BranchName=$(echo "${{ github.head_ref }}" | sed 's/^refs\/heads\///')
          COMMIT=${COMMIT:-60322a3b12be012f77a22a6004d22d02bc048303}

          cd /tmp
          mkdir init && cd init
          wget -c https://raw.githubusercontent.com/RSKYS/SBo-git/$COMMIT/system/sbotools/sbotools.SlackBuild \
                  https://raw.githubusercontent.com/RSKYS/SBo-git/$COMMIT/system/sbotools/sbotools.info \
                  https://raw.githubusercontent.com/RSKYS/SBo-git/$COMMIT/system/sbotools/slack-desc \
                  https://raw.githubusercontent.com/RSKYS/SBo-git/$COMMIT/system/sbotools/req.diff \
                  https://raw.githubusercontent.com/RSKYS/SBo-git/$COMMIT/system/sbotools/README

          export $( cat sbotools.info | \
                    grep -E "VERSION=|DOWNLOAD=" | tr -d "\"" )
          wget $DOWNLOAD

          TAG=red PKGTYPE=txz sh sbotools.SlackBuild
          upgradepkg --reinstall --install-new /tmp/sbotools-$VERSION*.t?z
          rm -rf {.git*,*}
          sbosnap fetch )

        ( cd /tmp/sbo/repo
          CHANGED=$(git diff --name-only remotes/origin/current.. | grep '.SlackBuild')
          find */*/ -name "doinst.sh" -exec sed -e '1,$d' {} +

          for FILE in $CHANGED; do
            BASENAME=$(basename $FILE .SlackBuild)

            PKGTYPE=txz \
                  sboinstall -j3 --reinstall $BASENAME
          done )
